
benfica:
    image: fabiosantoscode/benfica
    environment:
        - ENVIRONMENT_VARIABLE=true
    ports:
        - "8080:8080"


proxy:
    image: fabiosantoscode/proxy
    links:
        - benfica
    ports:
        - "8081:8081"

